name: Generate OIDC Token
description: Generate OIDC Token
# outputs:
#   OIDC_BASE64:
#     value: ${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}
#     description: The signed JWT encoded token

runs:
  using: composite
  steps:
    - name: Generate OIDC Token
      id: generate-oidc-token
      run: |
        OIDC_BASE64=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/SAG-Trial" | base64 -w 0)

        # echo $OIDC_BASE64

        # Sending as Output  
        echo -n "OIDC_BASE64=$OIDC_BASE64" >> $GITHUB_OUTPUT

        # Adding Mask
        echo "::add-mask::$OIDC_BASE64"
      shell: bash

    - name: Encrypt OIDC
      run: |
        # Encrypt the JWT
        echo ${{steps.generate-oidc-token.outputs.OIDC_BASE64}} | gpg --quiet --symmetric --cipher-algo AES256 --batch --yes --passphrase 'qm-passphrase' --output oidc.txt.gpg
      shell: bash
 
    - name: Upload OIDC as artifact
      uses: actions/upload-artifact@v4
      with:
        name: OIDC_BASE64
        path: oidc.txt.gpg
        retention-days: 1  

  # using: node16
  # main: dist/index.js
