name: Generate OIDC Token
description: Generate OIDC Token
outputs:
  signedJWTencoded:
    value: ${{ steps.generate-oidc-token.outputs.signedJWTencoded }}
    description: The signed JWT encoded token

runs:
  using: composite
  steps:
    - name: Generate OIDC Token
      id: generate-oidc-token
      run: |
        signedJWTencoded=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/SAG-Trial" | base64)

        # echo "::set-output name=signedJWTencoded::$signedJWTencoded"
        echo "signedJWTencoded=$signedJWTencoded" >> $GITHUB_OUTPUT
      shell: bash


  # using: node16
  # main: dist/index.js