name: Generate OIDC Token
description: Generate OIDC Token
outputs:
  signedJWTencoded:
    value: ${{ steps.generate-oidc-token.outputs.SIGNED_JWT_ENCODED_BASE64 }}
    description: The signed JWT encoded token

runs:
  using: composite
  steps:
    - name: Generate OIDC Token
      id: generate-oidc-token
      run: |
        SIGNED_JWT_ENCODED_BASE64=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/SAG-Trial" | base64 -w 0)

        # echo "::set-output name=SIGNED_JWT_ENCODED_BASE64::$SIGNED_JWT_ENCODED_BASE64"
        echo "SIGNED_JWT_ENCODED_BASE64=$SIGNED_JWT_ENCODED_BASE64" >> $GITHUB_OUTPUT
      shell: bash


  # using: node16
  # main: dist/index.js