name: Generate OIDC Token
description: Generate OIDC Token
outputs:
  OIDC_BASE64:
    value: ${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}
    description: The signed JWT encoded token

runs:
  using: composite
  steps:
    - name: Generate OIDC Token
      id: generate-oidc-token
      run: |
        OIDC_BASE64=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/SAG-Trial" | base64 -w 0)

        # Encrypt the JWT
        OIDC_BASE64_ENCRYPTED=$(echo $SIGNED_JWT_ENCODED_BASE64 | gpg --symmetric --quiet --batch --passphrase "qm-passphrase" --output - | base64 -w0)

        # echo $OIDC_BASE64

        # Sending Encrypted as Output  
        echo -n "OIDC_BASE64=$OIDC_BASE64" >> $GITHUB_OUTPUT

        # Adding Mask
        echo "::add-mask::$OIDC_BASE64"
      shell: bash

  # using: node16
  # main: dist/index.js
