name: QM Reusable Secret Action
description: A Docker action to extract required secret
outputs:
  weather_api:  # id of output
    description: 'Weather API Key'
  # myOutput:  # id of output
  #   description: 'Output from node container'
  # workflow:  # id of output
  #   description: 'Whole Github Context'
  # githubActionPath:  # id of output
  #   description: 'GitHub workflow'
  

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT: weather
  
    

  
  
  