name: Custom Docker Container
description: A Dcoker container to extract secrets
outputs:
  WEATHER_API_SECRET:  # id of output
    # value: ${{ steps.get_secret_from_docker_container.outputs.WEATHER_API_SECRET }}
    description: 'An api key for weather api'

runs:
  using: docker
  image: 'Dockerfile'
  env:
    GITHU_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  