name: Checkout Private Repo
description: Checkout Private Repo
inputs:
  SSH_KEY:
    description: 'SSH Key for Private Repo'
    required: true
outputs:
  apiKey:  # id of output
      value: ${{ steps.qm-password-repo-action.outputs.output }}
      description: 'An api key requested from the password repo'    

runs:
  using: composite
  steps:
    - name: Checkout Main Repo
      uses: actions/checkout@v3

    - name: Checkout Private Repo
      uses: actions/checkout@v3
      with:
        ref: main
        repository: SAG-Trial/SecretSubModule
        ssh-key: '${{ inputs.SSH_KEY }}'
        path: .github/actions

    - name: Call Private from Internal (SubModule)
      id: call-private-from-internal
      uses: ./.github/actions/.github/actions/SendPasswordFile
      with:
        passwordIndex: weather_api_key

    - name: Cleanup
      run: |
        rm -rf .github/actions/QMPasswordRepo
      shell: bash     

    