name: Calls an action with PAT from Internal to Private
description: Calls an action with PAT from Internal to Private
inputs:
  SSH_PRIVATE_KEY:
    description: 'SSH Key'
    required: true


runs:
  using: composite
  steps:
    
    - name: Check out main repository
      uses: actions/checkout@v3 

    # - name: Decode SSH Key
    #   id: decode-ssh-key
    #   run: |
    #     ECHO_KEY=$(echo ${{ inputs.SSH_PRIVATE_KEY }} | sed -e 's/\(.\)/\1 /g')
    #     echo "ECHO_KEY=$ECHO_KEY"
        
    #   shell: bash    

    - name: Checkout Private Repo
      uses: actions/checkout@v3
      with:
        ref: main
        repository: SAG-Trial/SecretSubModule
        ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        path: .github/actions

    - name: Call Private from Internal (SubModule)
      id: call-private-from-internal
      uses: ./.github/actions/.github/actions/SendPasswordFile
      with:
        passwordIndex: weather_api_key

    - name: Get Weather
      uses: SAG-Trial/QM/.github/actions/GetWeather@main
      env:
          PASSWORD: ${{ steps.call-private-from-internal.outputs.output }}
  