name: Calls an action with PAT from Internal to Private
description: Calls an action with PAT from Internal to Private
inputs:
  SSH_PRIVATE_KEY:
    description: 'SSH Key'
    required: true


runs:
  using: composite
  steps:
    - name: Check GITHUB_ACTION_PATH
      run: |
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        cat $GITHUB_ACTION_PATH
        tree $GITHUB_ACTION_PATH 
      shell: bash

    - name: Check out main repository
      uses: actions/checkout@v3

    - name: Check GITHUB_ACTION_PATH
      run: |
        echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH"
        cat $GITHUB_ACTION_PATH
        tree $GITHUB_ACTION_PATH 
      shell: bash  

    - name: Checkout Private Repo
      uses: actions/checkout@v3
      with:
        ref: main
        repository: SAG-Trial/SecretSubModule
        ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        path: .github/actions

    - name: Call Private from Internal (SubModule)
      id: call-private-from-internal
      uses: ./.github/actions/.github/actions/SendPasswordFile

    - name: Get Weather
      uses: SAG-Trial/QM/.github/actions/GetWeather@main
      env:
          PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}
  