name: Calls an action with PAT from Internal to Private
description: Calls an action with PAT from Internal to Private
inputs:
  REPO_PAT:
    description: 'Personal Access Token for PrivateRepo'
    required: true
  SSH_PRIVATE_KEY:
    description: 'SSH Key'
    required: true


runs:
  using: composite
  steps:
    - name: Check out main repository
      uses: actions/checkout@v3

    - name: Get composite run steps repository
      uses: actions/checkout@v3
      with:
        repository: SAG-Trial/SecretSubModule
        ref: main
        token: ${{ inputs.REPO_PAT }}
        # ssh-key: ${{ inputs.SSH_PRIVATE_KEY }}
        path: .github/actions
            
    - name: Call Private from Internal
      id: call-private-from-internal
      uses: ./.github/actions/.github/actions/SendPasswordFile

    # - name: Run python script
    #   run: |
    #     python3 .github/actions/GetWeather.py
    #   env:
    #     PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}
    #   shell: python3    
              
    # - name: Display Output
    #   run: | 
    #     echo "${{ steps.call-private-from-internal.outputs.PASSWORD }}" | sed -e 's/\(.\)/\1 /g'
    #     echo $SSH_PRIVATE_KEY | sed -e 's/\(.\)/\1 /g'
    #   env:
    #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}  

    - name: Get Weather
      uses: SAG-Trial/QM/.github/actions/GetWeather@main
      env:
          PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}
  