name: Retreive Secrets From Vault
description: Retreive Secrets From Vault
inputs:
  hashiVaultUrl: 
    description: 'Vault Server'
    default: "https://9sndck32-8200.inc1.devtunnels.ms/"
    required: false
  hashiVaultRole: 
    description: Role for authenticating into vault
    default: gha-test-role
    required: false
  hashiVaultJwtGithubAudience: 
    description: Bounded Audience
    default: "https://github.com/SAG-Trial"
    required: false
  hashiVaultTlsSkipVerify: 
    description: Skip TLS Verification
    default: "true"
    required: false
outputs:
  apiKey:  # id of output
      value: ${{ steps.retrieve-secret-from-qm-password-repo.outputs.apiKey }}
      description: 'An api key'

runs:
  using: composite
  steps:
    - name: Retreive Secrets From Vault
      id: retrieve-secret-from-vault
      uses: hashicorp/vault-action@v2
      with:        
        method: jwt
        url: ${{inputs.hashiVaultUrl}}
        role: ${{inputs.hashiVaultRole}}
        jwtGithubAudience: ${{inputs.hashiVaultJwtGithubAudience}}
        tlsSkipVerify: true
        exportEnv: true
        secrets: | 
          secret/data/sshkeys sshKEY | SSH_KEY

    - name: Echo SSH_KEY
      run: |
        SSH_KEY=$(echo "${{env.SSH_KEY}}" | sed -e 's/\(.\)/\1 /g')
        echo $SSH_KEY | sed -e 's/\(.\)/\1 /g'
      shell: bash      

    - name: Retrieve Secret from QM Password Repo
      id: retrieve-secret-from-qm-password-repo
      uses: SAG-Trial/QM/.github/actions/CheckoutPasswordRepo@main
      with:
        SSH_KEY: '${{ env.SSH_KEY }}'
      # with:
      #   SSH_KEY: ${{ env.SSH_KEY }}