name: Composite Action for Node passing constants
description: Reusable action to get weather data without giving consumer the API key



runs:
  using: composite
  steps:
    - name: Call node action
      id: node-docker-action
      uses: SAG-Trial/QM/.github/actions/NodeDockerImage@main
      
    - name: Displaying outputs
      run: |
        # echo ${{steps.node-docker-action.outputs.myOutput}}
        # echo ${{steps.node-docker-action.outputs.workflow}}
        echo ${{steps.node-docker-action.outputs.weather_api}}
      shell: bash