name: Decrypt and verify JWT Token
description: Decrypt and verify JWT Token and extract payload
inputs:
  signedJWTbase64encoded:
    description: The signed JWT encoded token
    required: true
outputs:
  JWTTokenVerified:
    value: ${{ steps.verify-parent-token.outputs.JWTTokenVerified }}
    description: Returns "true" or "false" 

runs:
  using: composite
  steps:
    - name: Download OIDC from artifact
      uses: actions/download-artifact@v4
      with:
        name: OIDC_BASE64
        
    - name: Decrypt JWT Token
      id: decrypt-jwt-token
      run: |
        # Decrypt the JWT
        gpg --quiet --batch --yes --decrypt --passphrase='qm-passphrase' --output oidc.txt oidc.txt.gpg

        SIGNED_JWT_ENCODED_BASE64_DECRYPTED=$(cat oidc.txt)

        # Adding Mask
        echo "::add-mask::$SIGNED_JWT_ENCODED_BASE64_DECRYPTED"

        echo "PARENT_TOKEN=$SIGNED_JWT_ENCODED_BASE64_DECRYPTED" >> $GITHUB_OUTPUT

        rm -rf oidc.txt oidc.txt.gpg
      shell: bash

    - uses: geekyeggo/delete-artifact@v4
      with:
        token: ${{ github.token }}
        name: OIDC_BASE64

    - name: Verify Parent's JWT Token
      id: verify-parent-token
      uses: SAG-Trial/QM/.github/actions/VerifyJWTToken@main
      with: 
        signedJWTbase64encoded: ${{ steps.decrypt-jwt-token.outputs.PARENT_TOKEN }}