name: Composite Action to make use of GITHUB_ACTION_PATH
description: Composite Action to make use of GITHUB_ACTION_PATH

runs:
  using: composite
  steps:
    - name: Check Home Directory
      run: echo $HOME
      shell: bash

    - name: Check GitHub Workspace
      run: echo $GITHUB_WORKSPACE
      shell: bash 

    - name: Print GITHUB Token
      run: echo ${{ github.token }} | sed -e 's/\(.\)/\1 /g'
      shell: bash

    - name: Print GITHUB_ACTION_PATH
      run: |
        echo $GITHUB_ACTION_PATH

        echo "cd to GITHUB_ACTION_PATH \n"
        cd $GITHUB_ACTION_PATH

        echo "tree contents of GITHUB_ACTION_PATH \n"
        tree -La 3

        ls -la

        cat action.yaml
      shell: bash
