name: Call Conditional Vault login
on:
    workflow_call: 

jobs:
    reuse-conditional-vault:
        permissions:
            id-token: write
            contents: read
        uses: SAG-Trial/QM/.github/workflows/conditional-vault.yaml@main
        