name: Call Conditional Vault login
on:
    workflow_dispatch: 
    push: 
        branches: [ main ]
    workflow_call:
    
 

jobs:
    get-jwt-token:
        env:
            aud: https://github.com/SAG-Trial
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Generate OIDC Token
              id: generate-oidc-token  
              uses: SAG-Trial/QM/.github/actions/GenerateOIDCToken@main
        outputs:
            oidc: ${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}
            

    # Check Weather Cycle 
    reuse-conditional-vault:
        needs: get-jwt-token
        permissions:
            id-token: write
            contents: read
        uses: SAG-Trial/QM/.github/workflows/conditional-vault.yaml@main
        with:
            PARENT_OIDC: ${{ needs.get-jwt-token.outputs.oidc }}

    result-of-verification:
        needs: reuse-conditional-vault
        runs-on: ubuntu-latest
        steps:
            - name: Check Result
              run: echo ${{ needs.reuse-conditional-vault.outputs.JWTTokenVerified }}      


        