name: Conditional Vault OIDC Login
on:
    workflow_call: 
      inputs:
        PARENT_TOKEN:
          description: 'Parent token'
          required: true
          type: string
    repository_dispatch: 
    

jobs:
    validate-job:
        # if: github.action_repository
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: token from parent
              run: |
                echo ${{ inputs.PARENT_TOKEN }} 

            - name: Generate OIDC Token
              id: generate-oidc-token  
              uses: SAG-Trial/QM/.github/actions/GenerateOIDCToken@main