name: Conditional Vault OIDC Login
on:
    workflow_call: 
      inputs:
        PARENT_OIDC:
          description: 'Parent token'
          required: true
          type: string
    repository_dispatch: 
    

jobs:
    validate-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Verify Parent's JWT Token
              id: verify-parent-token
              uses: SAG-Trial/QM/.github/actions/VerifyJWTToken@main
              with: 
                signedJWTbase64encoded: ${{ inputs.PARENT_OIDC }}

            - name: Display Parent's JWT token verification
              run: echo ${{ steps.verify-parent-token.outputs.JWTTokenVerified }}  