name: Conditional Vault OIDC Login
on:
    workflow_call: 
    repository_dispatch: 
    

jobs:
    validate-job:
        # if: github.action_repository
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: token curl
              run: |
                curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
                jq "{ jwt: .value, role: \"${{env.roleName}}\" }" > ./token.json

                echo 'GitHub Actions Token Claims'
                cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq