name: Conditional Vault OIDC Login
on:
    workflow_call: 
      inputs:
        PARENT_OIDC:
          description: 'Parent token'
          required: false
          type: string
      outputs:
        JWTTokenVerified:
          value: ${{ jobs.validate-job.outputs.JWTTokenVerified }}
          description: 'True or false value if JWT token is verified'   
    repository_dispatch: 
    

jobs:
    validate-job:
      # if: github.event.inputs.PARENT_OIDC != null
        runs-on: ubuntu-latest
        outputs:
          JWTTokenVerified: ${{ steps.verify-parent-token.outputs.JWTTokenVerified }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # - run: echo ${{ inputs.PARENT_OIDC }}  

            - name: Verify Parent's JWT Token
              id: verify-parent-token
              uses: SAG-Trial/QM/.github/actions/VerifyJWTToken@main
              with: 
                signedJWTbase64encoded: ${{ inputs.PARENT_OIDC }}

        

