name: Conditional Vault OIDC Login
on:
    workflow_call: 
    repository_dispatch: 
    

jobs:
    validate-job:
        # if: github.action_repository
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check ACTIONS_ID_TOKEN_REQUEST_TOKE
              run: echo $ACTIONS_ID_TOKEN_REQUEST_TOKE
              
            - name: Check ACTIONS_ID_TOKEN_REQUEST_URL
              run: echo $ACTIONS_ID_TOKEN_REQUEST_URL