name: Get assignees from iTrac Filter (cloud-Open-blocker)

on:
  workflow_dispatch:  

jobs:
  get_assignees_open_blockers:
    name: Get assignees from iTrac Filter (cloud-Open-blocker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run API Request
        id: get_assignees_open_blockers
        uses: actions/javascript-action@v1
        env:
           ITRAC_API_TOKE: ${{secrets.ITRAC_TOKEN}} 

      - name: Display API Response
        run: echo ${{ steps.get_assignees_open_blockers.outputs.ASSIGNEES }}
