name: Runs Custom Docker action to use git secret

on:
    workflow_dispatch: 
    push: 
        branches: [ main ]    

jobs:
    git-secret-docker:
        name: Git Secret Docker (Custom Docker Action)
        runs-on: ubuntu-latest
        

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # - uses: Kingmidas74/git-secret-github-action@main
            #   with:
            #     # Prefix for installation
            #     # Default: usr/local
            #     prefix: ''

            # - name: Initialize git-secret
            #   run: git secret init
            
            # - name: Git Secret Docker
            #   uses: SAG-Trial/QM/.github/actions/GitSecretDocker@main
            - name: Checkout
              uses: actions/checkout@v3

              # Authenticating to Docker GitHub Registry
            - name: Docker login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}    

            
            - name: Custom QM-Secrets Image Docker
              uses: SAG-Trial/QM/.github/actions/DockerCustomImage@main
              

            # - name: Simulate Entrypoint
            #   run: |
            #     chmod +x entrypoint.sh
            #     ./entrypoint.sh

            # - name: Push changes
            #   uses: ad-m/github-push-action@master
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     branch: ${{ github.ref }}


        