name: Runs Custom Docker action to use git secret

on:
    workflow_call:
      outputs:
        password: 
          description: "The required password"
          value: ${{jobs.secret-image-container-job.outputs.WEATHER_API_KEY}}

    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    secret-image-container-job:
        outputs:
          WEATHER_API_KEY: ${{steps.retrieve-secret.outputs.WEATHER_API_KEY}}
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        
        container: 
          image: ghcr.io/sag-trial/secret-image:1.1
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
          # - name: Retrieve secret
          #   id: retrieve-secret
          #   uses: SAG-Trial/QM/.github/actions/RetrieveSecrets@main

          # - name: Retrieve secret
          #   id: retrieve-secret
          #   run: |
          #     #!/bin/bash

          #     # Check if the INPUT environment variable is set
          #     if [ -n "$INPUT" ]; then
          #         # Check if INPUT equals "weather"
          #         if [ "$INPUT" = "weather" ]; then
          #             # Send the content of .env to GITHUB_OUTPUT
          #             if [ -f "/secrets/.env" ]; then
          #                 CONTENT=$(cat /secrets/.env | grep "^WEATHER_API=" | awk -F '=' '{print $2}'
          #                 )
          #                 echo "WEATHER_API_KEY=$CONTENT" >> $GITHUB_OUTPUT
          #             else
          #                 echo "Error: .env file not found"
          #                 exit 1
          #             fi
          #         else
          #             echo "Error: INPUT is not set to 'weather'"
          #             exit 1
          #         fi
          #     else
          #         echo "Error: INPUT environment variable not set"
          #         exit 1
          #     fi

          #     # If everything is successful, exit with a success code (0)
          #     exit 0

          - name: Check Home Directory
            run: echo $HOME
            
          - name: List /github/home contents
            run: |
              pwd 
              tree -La 3 /github/home

          - name: Check GitHub Workspace
            run: echo $GITHUB_WORKSPACE

            # Isolating a unique variable  
          # - name: Check Github Workflow name
          #   run: echo ${{github.workflow}}

          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Dump job context
            env:
              JOB_CONTEXT: ${{ toJson(job) }}
            run: echo "$JOB_CONTEXT"

          - name: Dump steps context
            env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
            run: echo "$STEPS_CONTEXT"

          - name: Dump runner context
            env:
              RUNNER_CONTEXT: ${{ toJson(runner) }}
            run: echo "$RUNNER_CONTEXT"

          - name: Github event trigger
            run: echo ${{ github.event }}

    # verifying-output:
    #   runs-on: ubuntu-latest
    #   needs: secret-image-container-job
    #   steps:
    #     - name: Display the output
    #       run: echo ${{needs.secret-image-container-job.outputs.WEATHER_API_KEY}}

    #     - name: Get Weather
    #       uses: SAG-Trial/QM/.github/actions/GetWeather@main
    #       env:
    #           PASSWORD: ${{ needs.secret-image-container-job.outputs.WEATHER_API_KEY }}

        
    # get-ouput-from-container-job:
    #     name: Test Container Job and it's output

            # - uses: Kingmidas74/git-secret-github-action@main
            #   with:
            #     # Prefix for installation
            #     # Default: usr/local
            #     prefix: ''

            # - name: Initialize git-secret
            #   run: git secret init
            
            # - name: Git Secret Docker
            #   uses: SAG-Trial/QM/.github/actions/GitSecretDocker@main

            # Authenticating to Docker GitHub Registry
            # - name: Docker login
            #   uses: docker/login-action@v3
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.GITHUB_TOKEN }}
            
            # - name: Custom QM-Secrets Image Docker
            #   uses: SAG-Trial/QM/.github/actions/DockerCustomImage@main 
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

            # - name: Check Home Directory
            #   run: echo $HOME

            # - name: List / contents
            #   run: | 
            #     cd /
            #     tree -La 3

            # - name: Check GitHub Workspace
            #   run: echo $GITHUB_WORKSPACE

            # # Isolating a unique variable  
            # - name: Check Github Workflow name
            #   run: echo ${{github.workflow}}

            # - name: Dump GitHub context
            #   env:
            #     GITHUB_CONTEXT: ${{ toJson(github) }}
            #   run: echo "$GITHUB_CONTEXT"

            # - name: Dump job context
            #   env:
            #     JOB_CONTEXT: ${{ toJson(job) }}
            #   run: echo "$JOB_CONTEXT"

            # - name: Dump steps context
            #   env:
            #     STEPS_CONTEXT: ${{ toJson(steps) }}
            #   run: echo "$STEPS_CONTEXT"

            # - name: Dump runner context
            #   env:
            #     RUNNER_CONTEXT: ${{ toJson(runner) }}
            #   run: echo "$RUNNER_CONTEXT"



        