name: Runs Custom Docker action to use git secret

on:
    workflow_call: 
    workflow_dispatch: 
    push: 
        branches: [ main ]

jobs:
    login-private-registry:
        name: Custom Container Job passing secrets
        runs-on: ubuntu-latest
        # output: 
        container: 
          image: ghcr.io/sag-trial/secret-image:latest
          env:
            INPUT: weather
          credentials:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        steps:
          - uses: actions/checkout@v3

    
    # get-ouput-from-container-job:
    #     name: Test Container Job and it's output

            # - uses: Kingmidas74/git-secret-github-action@main
            #   with:
            #     # Prefix for installation
            #     # Default: usr/local
            #     prefix: ''

            # - name: Initialize git-secret
            #   run: git secret init
            
            # - name: Git Secret Docker
            #   uses: SAG-Trial/QM/.github/actions/GitSecretDocker@main

            # Authenticating to Docker GitHub Registry
            # - name: Docker login
            #   uses: docker/login-action@v3
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.actor }}
            #     password: ${{ secrets.GITHUB_TOKEN }}
            
            # - name: Custom QM-Secrets Image Docker
            #   uses: SAG-Trial/QM/.github/actions/DockerCustomImage@main 
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

            # - name: Check Home Directory
            #   run: echo $HOME

            # - name: List / contents
            #   run: | 
            #     cd /
            #     tree -La 3

            # - name: Check GitHub Workspace
            #   run: echo $GITHUB_WORKSPACE

            # # Isolating a unique variable  
            # - name: Check Github Workflow name
            #   run: echo ${{github.workflow}}

            # - name: Dump GitHub context
            #   env:
            #     GITHUB_CONTEXT: ${{ toJson(github) }}
            #   run: echo "$GITHUB_CONTEXT"

            # - name: Dump job context
            #   env:
            #     JOB_CONTEXT: ${{ toJson(job) }}
            #   run: echo "$JOB_CONTEXT"

            # - name: Dump steps context
            #   env:
            #     STEPS_CONTEXT: ${{ toJson(steps) }}
            #   run: echo "$STEPS_CONTEXT"

            # - name: Dump runner context
            #   env:
            #     RUNNER_CONTEXT: ${{ toJson(runner) }}
            #   run: echo "$RUNNER_CONTEXT"
    
            
                
    # custom-docker-action:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Custom QM-Secrets Image Docker
    #       uses: SAG-Trial/QM/.github/actions/DockerCustomImage@main
              
            # - name: Simulate Entrypoint
            #   run: |
            #     chmod +x entrypoint.sh
            #     ./entrypoint.sh

            # - name: Push changes
            #   uses: ad-m/github-push-action@master
            #   with:
            #     github_token: ${{ secrets.GITHUB_TOKEN }}
            #     branch: ${{ github.ref }}


        