name: Runs Custom Docker action to use git secret

on:
    workflow_dispatch: 
    push: 
        branches: [ main ]    

jobs:
    git-secret-docker:
        name: Git Secret Docker (Custom Docker Action)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: Kingmidas74/git-secret-github-action@main
              with:
                # Prefix for installation
                # Default: usr/local
                prefix: ''
            
            # - name: Git Secret Docker
            #   uses: SAG-Trial/QM/.github/actions/GitSecretDocker@main

        