name: Node Action Test
on:
    workflow_dispatch: 
    push: 
        branches: [ main ]


jobs:
    call-node-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Call node action
              uses: SAG-Trial/QM/.github/actions/CompositeNodeAction@main