name: Get Weather Data through Vault Login
on:
    workflow_dispatch: 
    push: 
        branches: [ main ]
    workflow_call:
  
env: 
    GLOBAL_VARIABLE: "Global Variable"
        
jobs:
    generate-jwt-token:
        name: Generate a Workflow JWT Token for authorization to Vault
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Generate OIDC Token
              id: generate-oidc-token  
              uses: SAG-Trial/QM/.github/actions/GenerateOIDCToken@main  

            - name: Set to Env variable
              run: echo "GLOBAL_VARIABLE=${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}" >> $GITHUB_ENV"    
        # outputs:
        #     oidc: ${{ steps.generate-oidc-token.outputs.OIDC_BASE64 }}
            
    # Get Weather Key 
    reuse-vault-login:
        name: Reuse Vault Login Workflow And Get Key
        needs: generate-jwt-token
        permissions:
            id-token: write
            contents: read
        uses: SAG-Trial/QM/.github/workflows/reusable-vault-login.yaml@main
        with:
            PARENT_OIDC: ${{ needs.generate-jwt-token.outputs.oidc }}
            # PARENT_OIDC: ${{ env.GLOBAL_VARIABLE }}

    get-weather-data:
        name: Get Weather Data after Vault Login
        needs: reuse-vault-login
        runs-on: ubuntu-latest
        steps:        
            - name: Get Weather
              uses: SAG-Trial/QM/.github/actions/GetWeather@main
              env: 
                # PASSWORD: ${{ needs.reuse-vault-login.outputs.weatherKey }}   
                PASSWORD: ${{ env.GLOBAL_VARIABLE }}   
      


        