name: Read the file from a secret submodule
on:
    workflow_call: 

jobs:
    get-content-from-probot:
        # name: Get content from probot
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3


  