name: Calls an action with PAT from Internal to Private
on:
    workflow_dispatch: 
    push: 
      branches: [ main ]   

    workflow_call: 
      # outputs:
      #   PASSWORD: 
      #     description: 'Weather API Key'
      #     value: ${{ jobs.call-private-from-internal.outputs.PASSWORD }}
          
jobs:
    call-private-from-internal:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Private Repo
              uses: actions/checkout@v3
              with:
                repository: SAG-Trial/SecretSubModule
                ssh-key: ${{ secrets.ORG_PRIVATEREPO_SSH }}
                path: private_action

            - run: |
                cd private_action
                ls -la

                pwd
                # cd .github/actions/SendPasswordFile

                tree .github  

            - name: Call Private Repo Action
              id: call-private-repo-action
              uses: /.github/actions/SendPasswordFile@main
              
            - name: GetWeather
              uses: SAG-Trial/QM/.github/actions/GetWeather@main
              env:
                PASSWORD: ${{ steps.call-private-repo-action.outputs.PASSWORD }}
