name: Calls an action with PAT from Internal to Private
on:
    workflow_dispatch: 
    # push: 
    #   branches: [ main ]   

    workflow_call: 
      # outputs:
      #   PASSWORD: 
      #     description: 'Weather API Key'
      #     value: ${{ jobs.call-private-from-internal.outputs.PASSWORD }}
          
jobs:
    call-private-from-internal:
        name: Call Private from Internal
        uses: SAG-Trial/QM/.github/workflows/git-secret