name: Calls an action with PAT from Internal to Private
on:
    workflow_dispatch: 

    workflow_call: 
      # outputs:
      #   PASSWORD: 
      #     description: 'Weather API Key'
      #     value: ${{ jobs.call-private-from-internal.outputs.PASSWORD }}
          
jobs:
    call-private-from-internal:
        name: Call Private from Internal
        runs-on: ubuntu-latest
        outputs:
          PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}

        steps:
            - name: Check out main repository
              uses: actions/checkout@v3

            - name: "Get Application Token" 
              id: get_app_token 
              uses: tibdex/github-app-token@v1 
              with: 
                app_id: ${{ secrets.APP_ID }} 
                private_key: ${{ secrets.APP_SECRET }}   

            - name: Get composite run steps repository
              uses: actions/checkout@v3
              with:
                repository: SAG-Trial/SecretSubModule
                ref: main
                token: ${{ steps.get_app_token.outputs.token }}
                # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                path: .github/actions
            
            - name: Call Private from Internal
              id: call-private-from-internal
              uses: ./.github/actions/.github/actions/SendPasswordFile
              
            # - name: Display Output
            #   run: | 
            #     echo "${{ steps.call-private-from-internal.outputs.PASSWORD }}" | sed -e 's/\(.\)/\1 /g'
            #     echo $SSH_PRIVATE_KEY | sed -e 's/\(.\)/\1 /g'
            #   env:
            #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}  

            - name: Get Weather
              uses: SAG-Trial/QM/.github/actions/GetWeather@main
              env:
                  PASSWORD: ${{ steps.call-private-from-internal.outputs.PASSWORD }}