name: Calls an action with PAT from Internal to Private
on:
    workflow_call: 
          
      
jobs:
    call-private-from-internal:
        name: Call Private from Internal
        runs-on: ubuntu-latest
        steps:
            - name: Check out main repository
              uses: actions/checkout@v3

            - name: Get composite run steps repository
              uses: actions/checkout@v3
              with:
                repository: SAG-Trial/SecretSubModule
                ref: main
                # token: ${{ secrets.REPO_PAT }}
                ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
                path: .github/actions
            

            - name: Call Private from Internal
              id: call-private-from-internal
              uses: ./.github/actions/.github/actions/SendPasswordFile
              
            - name: Display Output
              run: echo "${{ steps.call-private-from-internal.outputs.connector }}" | sed -e 's/\(.\)/\1 /g'