name: Calls an action with PAT from Internal to Private
on:
    workflow_dispatch: 
    push: 
      branches: [ main ]   

    workflow_call: 
      # outputs:
      #   PASSWORD: 
      #     description: 'Weather API Key'
      #     value: ${{ jobs.call-private-from-internal.outputs.PASSWORD }}
          
jobs:
    call-private-from-internal:
        runs-on: ubuntu-latest
        steps:
            - name: Read Private from Internal (Composite)
              uses: SAG-Trial/QM/.github/actions/ReadCompositeActionInternalPrivate@main
              with:
                SSH_PRIVATE_KEY: ${{ secrets.ORG_PRIVATEREPO_SSH }}

            # - name: Get composite run steps repository
            #   uses: actions/checkout@v3
            #   with:
            #     repository: SAG-Trial/SecretSubModule
            #     ref: main
            #     token: ${{ secrets.REPO_PAT }}
            #     token: ${{ steps.get_app_token.outputs.token }}
            #     ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            #     path: .github/actions

            # Set up git config
            # - name: Set up git config
            #   run: |
            #     git config --global user.email "you@example.com" && git config --global user.name "Your Name"

            # Read File Contents
            # - name: Read File contents
            #   run: |
            #     cd .github/actions/SecretSubModule
            #     git submodule update --init
            #     ls -la
            
            # Calling Action in SubModule within QM repository
            # - name: Call Private from Internal (SubModule)
            #   id: call-private-from-internal
            #   # uses: SAG-Trial/SecretSubModule/.github/actions/SendPasswordFile@main
            #   uses: ./.github/actions/SecretSubModule/.github/actions/SendPasswordFile@main
              
            # - name: Display Output
            #   run: | 
            #     echo "${{ steps.call-private-from-internal.outputs.PASSWORD }}" | sed -e 's/\(.\)/\1 /g'
            #     echo $SSH_PRIVATE_KEY | sed -e 's/\(.\)/\1 /g'
            #   env:
            #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}      
