name: Reusable Vault OIDC Login
on:
    workflow_call: 
      inputs:
        PARENT_OIDC:
          description: 'Parent token'
          required: false
          type: string
      outputs:
        weatherKey:
          value: ${{ jobs.reusable-vault-login.outputs.weatherString }}
          description: 'True or false value if JWT token is verified'   
    repository_dispatch: 
    
env:
  WEATHER_KEY: initial_value

jobs:
    reusable-vault-login:
        name: Reusable Vault Login
        runs-on: ubuntu-latest
        outputs:
          weatherString: ${{ steps.send-key-output.outputs.weatherKey }}
        steps:


            - name: Verify Parent's JWT Token
              id: verify-parent-token
              uses: SAG-Trial/QM/.github/actions/VerifyJWTToken@main
              with: 
                signedJWTbase64encoded: ${{ inputs.PARENT_OIDC }}

            - name: Retreive Secrets From Vault
              if: ${{steps.verify-parent-token.outputs.JWTTokenVerified == 'true' && steps.verify-parent-token.outcome == 'success'}}  
              id: retrieve-secret-from-vault
              uses: hashicorp/vault-action@v2
              with:        
                method: oidc
                url: https://9sndck32-8200.inc1.devtunnels.ms/
                role: gha-test-role
                jwtGithubAudience: https://github.com/SAG-Trial
                tlsSkipVerify: true
                secrets: | 
                  secret/data/apikeys weatherApi | WEATHER_KEY

            # - name: Check Vault Token
            #   run: echo $VAULT_TOKEN | sed -e 's/\(.\)/\1 /g'  

            - name: Get Weather
              uses: SAG-Trial/QM/.github/actions/GetWeather@main
              env: 
                # PASSWORD: ${{ needs.reuse-vault-login.outputs.weatherKey }}   
                PASSWORD: ${{steps.retrieve-secret-from-vault.outputs.WEATHER_KEY }}  
            
            # - name: Set to Env variable
            #   run: echo "GLOBAL_VARIABLE=$WEATHER_KEY" >> $GITHUB_ENV"   

            # - name: Send Key output
            #   id: send-key-output
            #   run: | 
            #     MID_KEY=$WEATHER_KEY
            #     API_TOKEN_BASE64=`echo -n $MID_KEY | base64 -w 0`
            #     echo -n "weatherKey=$API_TOKEN_BASE64" >> $GITHUB_OUTPUT

             

        

