name: Reusable Vault OIDC Login
on:
    workflow_call: 
      inputs:
        PARENT_OIDC:
          description: 'Parent token'
          required: false
          type: string
      outputs:
        weatherKey:
          value: ${{ jobs.reusable-vault-login.outputs.weatherKey }}
          description: 'True or false value if JWT token is verified'   
    repository_dispatch: 
    
env:
  WEATHER_KEY: initial_value

jobs:
    reusable-vault-login:
        name: Reusable Vault Login
        runs-on: ubuntu-latest
        outputs:
          weatherKey: ${{ steps.send-key-output.outputs.weatherKey }}
        steps:
            - name: Verify Parent's JWT Token
              id: verify-parent-token
              uses: SAG-Trial/QM/.github/actions/VerifyJWTToken@main
              with: 
                signedJWTbase64encoded: ${{ inputs.PARENT_OIDC }}

            - name: Retreive Secrets From Vault
              if: ${{steps.verify-parent-token.outputs.JWTTokenVerified == 'true' && steps.verify-parent-token.outcome == 'success'}}  
              id: retrieve-secret-from-vault
              uses: hashicorp/vault-action@v2
              with:        
                method: jwt
                url: https://9sndck32-8200.inc1.devtunnels.ms/
                role: gha-test-role
                jwtGithubAudience: https://github.com/SAG-Trial
                exportEnv: true
                exportToken: true
                tlsSkipVerify: true
                secrets: | 
                  secret/data/apikeys weatherApi | WEATHER_KEY

            - name: Check Vault Token
              run: echo $VAULT_TOKEN | sed -e 's/\(.\)/\1 /g'      

            - name: Send Key output
              id: send-key-output
              run: echo "weatherKey=$WEATHER_KEY" >> $GITHUB_OUTPUT

             

        

