name: Review Step check

on:
  workflow_dispatch:
    inputs:
        proceed:
            description: 'GO/NOGO'
            type: boolean
            required: true
            default: false
    

jobs:
  get-proceed-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Proceed Status
        id: check-proceed-status
        run: |
          echo "Proceed Status: ${{ github.event.inputs.proceed }}"
        #   random_number=$((RANDOM % 2))

          # Use the random number to determine the output
        #   if [ "$random_number" -eq 0 ]; then
        #     echo "PROCEED_STATUS=GO" >> $GITHUB_OUTPUT
        #   else
        #     echo "PROCEED_STATUS=NOGO" >> $GITHUB_OUTPUT
        #   fi
            
      - name: Request Review step
        if: ${{ inputs.proceed == false}}
    #   if: ${{ steps.check-proceed-status.outputs.PROCEED_STATUS == 'NOGO' }}
        run: |
          exit 1  
