name: Vault OIDC Login

on:
    workflow_dispatch:
    push:
        branches:
            - main  

env:
  hashiUrl: https://9sndck32-8200.inc1.devtunnels.ms
  roleName: gha-test-role
  audience: https://github.com/SAG-Trial

jobs:
    hello:
        runs-on: ubuntu-latest
        name: Says Hello World
        permissions: 
            contents: read
            id-token: write
        steps:
            - name: Say it
              run: echo "Hello World"

            - name: Troubleshooting
              id: troubleshooting
              run: |
                  curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
                  jq "{ jwt: .value, role: \"${{env.roleName}}\" }" > ./token.json

                  echo 'GitHub Actions Token Claims'
                  cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq
          
                  echo 'Vault Login Response'
                  curl -o response.json -sSLf -X POST -H "Content-Type: application/json" -H "X-Vault-Namespace: admin" --data @token.json ${{env.hashiUrl}}/v1/auth/jwt/login

                  client_token=$(jq -r '.auth.client_token' ./response.json)

                  echo "client_token=$(jq -r '.auth.client_token' ./response.json)" >> $GITHUB_OUTPUT

                  echo $
          
                  # Remove the token file when we're done (if we don't fail)
                  # rm ./token.json

            - name: Retreive Secrets
              id: retrieve-secrets
              uses: hashicorp/vault-action@v2
              with:
                method: token
                token: root
                # path: secret/apikeys
                url: https://9sndck32-8200.inc1.devtunnels.ms
                # role: ${{ env.roleName }}
                # jwtGithubAudience: ${{ env.audience}}
                exportEnv: true
                tlsSkipVerify: true
                secrets: |
                  secret/data/apikeys weatherApi | WEATHER_KEY

            - name: Check Weather API Key
              run: |
                echo $WEATHER_KEY | | sed -e 's/\(.\)/\1 /g'
              env: 
                WEATHER_KEY: ${{ steps.retrieve-secrets.outputs.WEATHER_KEY }}        