name: Vault OIDC Login

on:
    workflow_call:
      outputs:
        WEATHER_KEY:
          description: 'Weather API Key'
          value: ${{ jobs.call-vault.outputs.WEATHER_KEY}}
        
    workflow_dispatch:
    push:
        branches:
            - main          

env:
  hashiUrl: https://9sndck32-8200.inc1.devtunnels.ms
  roleName: gha-test-role
  audience: https://github.com/SAG-Trial

jobs:
    call-vault:
        runs-on: [linux]
        name: Vault OIDC Login
        outputs:
          WEATHER_KEY: ${{ steps.retrieve-secrets.outputs.WEATHER_KEY }}
        permissions: 
            contents: read
            id-token: write
        steps:
            # - name: perform token run
            #   id: perform-token-run
            #   run: |
            #     echo jsonEncoded=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{env.audience}}" | base64)  

            - name: Troubleshooting
              id: troubleshooting
              run: |
                  curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
                  jq "{ jwt: .value, role: \"${{env.roleName}}\" }" > ./token.json

                  echo 'GitHub Actions Token Claims'
                  cat ./token.json | @base64d' | jq
          
                  echo 'Vault Login Response'
                  curl -sSLf -X POST -H "Content-Type: application/json" -H "X-Vault-Namespace: admin" --data @token.json ${{env.hashiUrl}}/v1/auth/jwt/login

            # - name: Retreive Secrets
            #   id: retrieve-secrets
            #   uses: hashicorp/vault-action@v2
            #   with:        
            #     method: jwt
            #     url: https://9sndck32-8200.inc1.devtunnels.ms
            #     role: ${{ env.roleName }}
            #     jwtGithubAudience: ${{ env.audience}}
            #     exportEnv: true
            #     tlsSkipVerify: true
            #     secrets: | 
            #       secret/data/apikeys weatherApi | WEATHER_KEY

            # # <--- Consuming steps ---->       
            # - name: Check Weather API Key and export as output
            #   id: check-weather-api-key
            #   run: |
            #     echo $WEATHER_KEY | sed -e 's/\(.\)/\1 /g'   
            #     echo "::set-output name=WEATHER_KEY::$WEATHER_KEY"   

            # - name: Get Weather
            #   uses: SAG-Trial/QM/.github/actions/GetWeather@main
            #   env: 
            #     PASSWORD: ${{ steps.check-weather-api-key.outputs.WEATHER_KEY }}